version: "3.9"

services:
  mysql:
    container_name: webdb
    restart: always
    build:
      context: db
      dockerfile: Dockerfile
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=webdb
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306

  api:
    container_name: web_api
    restart: unless-stopped
    build:
      context: server
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mysql
  
  client:
    container_name: web_client
    restart: unless-stopped
    build:
      context: ui
      dockerfile: Dockerfile
    ports:
      - 4200:4200
    depends_on:
      - api
